#include <iostream>
using namespace std;

int main(){
    int hp, atk, def, spAtk, spDef, spd;
    cin >> hp >> atk >> def >> spAtk >> spDef >> spd;

    cout <<
    "<table class='statTable'>\n"
    "    <tbody>\n"
    "        <tr class='statHeaders statRow'>\n"
    "            <th class='statHeader'>Stat</th>\n"
    "            <th class='statHeader'>Value</th>\n"
    "        </tr>\n"
    "        <tr class='statRow hp'>\n"
    "            <td class='statLabel'>\n"
    "                HP\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'></strong class='statNum'>" << hp << "</strong></span>\n"
    "                <meter class='statBar hpBar' min='0' max='255' value='" << hp << "'></meter>\n"
    "            </td>\n"
    "        </tr>\n"
    "        <tr class='statRow atk'>\n"
    "            <td class='statLabel'>\n"
    "                Attack\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'></strong class='statNum'>" << atk << "</strong></span>\n"
    "                <meter class='statBar atkBar' min='0' max='255' value='" << atk << "'></meter>\n"
    "           </td>\n"
    "        </tr>\n"
    "        <tr class='statRow def'>\n"
    "            <td class='statLabel'>\n"
    "                Defense\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'></strong class='statNum'>" << def << "</strong></span>\n"
    "                <meter class='statBar defBar' min='0' max='255' value='" << def << "'></meter>\n"
    "            </td>\n"
    "        </tr>\n"
    "        <tr class='statRow spAtk'>\n"
    "            <td class='statLabel'>\n"
    "                Sp. Attack\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'></strong class='statNum'>" << spAtk << "</strong></span>\n"
    "                <meter class='statBar spAtkBar' min='0' max='255' value='" << spAtk << "'></meter>\n"
    "            </td>\n"
    "        </tr>\n"
    "        <tr class='statRow'>\n"
    "            <td class='statLabel'>\n"
    "                Sp. Defense\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'></strong class='statNum'>" << spDef << "</strong></span>\n"
    "                <meter class='statBar spDefBar' min='0' max='255' value='" << spDef << "'></meter>\n"
    "            </td>\n"
    "        </tr>\n"
    "        <tr class='statRow spd'>\n"
    "            <td class='statLabel'>\n"
    "                Speed\n"
    "            </td>\n"
    "            <td class='statData'>\n"
    "                <span class='statNum'><strong class='statNum'>" << spd << "</strong></span>\n"
    "                <meter class='statBar spdBar' min='0' max='255' value='" << spd << "'></meter>\n"
    "            </td>\n"
    "        </tr>\n"
    "    </tbody>\n"
    "</table>\n";
}